
services:

  postgres:
    image: postgres:latest
    container_name: entity_reflection_postgres
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: entity_reflection_db
      PGDATA: /var/lib/data/postgresql

  entity-reflection:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/entity_reflection_db